#!/usr/bin/env bash
#
# ventoy-merge-theme.sh — safely merge a Raven Hub theme block into an
# existing Ventoy ventoy.json without touching any other plugin.
#
# What it does:
#   1. Validates BOTH files as JSON (and warns about duplicate keys, which
#      parsers normally resolve silently and which Ventoy may misread).
#   2. Writes a merged file that contains everything from YOUR existing
#      ventoy.json, with only the "theme" key replaced by the Raven Hub one.
#      All other plugins (control, menu_alias, menu_class, persistence,
#      auto_install, injection, password, image_list, ...) are preserved as-is.
#   3. NEVER overwrites your file unless you pass --in-place, and even then it
#      first saves a timestamped backup you can roll back to.
#
# Dependencies: jq (required), python3 (optional, for duplicate-key detection).
# Install jq with: sudo apt install jq | sudo dnf install jq | sudo pacman -S jq | brew install jq
#
# Exit codes: 0 success · 1 usage error · 2 missing dependency · 3 invalid input

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DUP_CHECK="${SCRIPT_DIR}/json_dup_check.py"

usage() {
cat << EOF
Usage: $0 --existing FILE --theme FILE [--output FILE] [--in-place]

Options:
  --existing FILE   Your current ventoy.json on the Ventoy USB (never modified
                    unless --in-place is given).
  --theme FILE      The Raven Hub 'ventoy.json' (theme-only) generated by
                    build-ventoy.sh; its "theme" object is what gets merged.
  --output FILE     Where to write the merged JSON (default: beside your file,
                    as ventoy.json.raven-hub-merged.json). Refuses to overwrite.
  --in-place        Replace --existing with the merged result after saving
                    ventoy.json.bak-YYYYmmdd-HHMMSS next to it.
  -h, --help        Show this help.

Examples:
  # Preview merge result (writes nothing over your file):
  $0 --existing /media/$USER/VENTOY/ventoy/ventoy.json \\
     --theme dist/ventoy/ventoy.json

  # Apply in place with automatic backup:
  $0 --existing /media/$USER/VENTOY/ventoy/ventoy.json \\
     --theme dist/ventoy/ventoy.json --in-place

Rollback (after --in-place):
  cp ventoy.json.bak-YYYYmmdd-HHMMSS ventoy.json
EOF
}

die() { local code="$1"; shift; echo "ERROR: $*" >&2; exit "${code}"; }
info() { echo "==> $*"; }

existing=""
theme_file=""
output=""
in_place="false"

while [[ $# -gt 0 ]]; do
  case "${1}" in
    --existing) existing="${2:-}" ; [[ -n "${existing}" ]] || die 1 "--existing needs a path"; shift 2 ;;
    --theme)    theme_file="${2:-}" ; [[ -n "${theme_file}" ]] || die 1 "--theme needs a path"; shift 2 ;;
    --output)   output="${2:-}" ; [[ -n "${output}" ]] || die 1 "--output needs a path"; shift 2 ;;
    --in-place) in_place="true"; shift ;;
    -h|--help)  usage; exit 0 ;;
    *) usage; echo; die 1 "unrecognized argument '${1}'" ;;
  esac
done

[[ -n "${existing}" && -n "${theme_file}" ]] || { usage; die 1 "both --existing and --theme are required"; }
[[ -f "${existing}" ]] || die 1 "existing ventoy.json not found: ${existing}"
[[ -f "${theme_file}" ]] || die 1 "theme ventoy.json not found: ${theme_file}"
command -v jq >/dev/null 2>&1 || die 2 "jq is required. Install it (e.g. 'sudo apt install jq'), then re-run."

# --- validate inputs ------------------------------------------------------
jq empty "${theme_file}"   || die 3 "theme file is not valid JSON: ${theme_file}"
jq empty "${existing}"     || die 3 "existing ventoy.json is not valid JSON: ${existing}"
jq -e 'type == "object"' "${existing}" >/dev/null || die 3 "existing ventoy.json must contain a JSON object"
jq -e 'type == "object" and has("theme")' "${theme_file}" >/dev/null || die 3 "theme file must contain a top-level \"theme\" object"

if command -v python3 >/dev/null 2>&1 && [[ -f "${DUP_CHECK}" ]]; then
  if ! python3 "${DUP_CHECK}" "${existing}" "${theme_file}"; then
    echo "WARNING: a duplicate key was found (see above). jq keeps only the LAST value of a" >&2
    echo "         duplicated key, which may not match your intent. Fix the file(s) first!" >&2
    die 3 "refusing to merge files with duplicate keys"
  fi
else
  echo "NOTE: python3 not found — duplicate-key detection skipped." >&2
fi

# Warn about architecture-specific theme overrides that would mask the merged theme.
masked="$(jq -r 'to_entries | map(select(.key | test("^theme_(legacy|uefi|ia32|aa64|mips)$"))) | map(.key) | join(", ")' "${existing}")"
if [[ -n "${masked}" ]]; then
  echo "WARNING: your ventoy.json already defines: ${masked}." >&2
  echo "         Those mode-specific objects take priority over \"theme\" in their boot modes." >&2
  echo "         Review them after the merge (see VENTOY.md, 'Multi-mode themes')." >&2
fi

# --- merge ----------------------------------------------------------------
# Everything except the "theme" key is carried over byte-for-value from the
# existing file; only "theme" is replaced with the Raven Hub object.
tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT
jq --slurpfile t "${theme_file}" '.theme = $t[0].theme' "${existing}" > "${tmp}"
jq empty "${tmp}" || die 3 "internal error: merged JSON failed validation"

echo
echo "Diff of the \"theme\" object (yours -> merged):"
if diff <(jq --sort-keys .theme "${existing}") <(jq --sort-keys .theme "${tmp}"); then
  info "the \"theme\" object is already identical — nothing to change."
fi
echo
info "all other keys preserved unchanged:"
comm -3 <(jq -r 'keys[]' "${existing}" | sort) <(jq -r 'keys[]' "${tmp}" | sort) || true

# --- write result ---------------------------------------------------------
if [[ "${in_place}" == "true" ]]; then
  backup="${existing}.bak-$(date +%Y%m%d-%H%M%S)"
  cp -p "${existing}" "${backup}"
  cat "${tmp}" > "${existing}"
  info "wrote merged config: ${existing}"
  info "backup saved as:     ${backup}"
else
  [[ -z "${output}" ]] && output="${existing}.raven-hub-merged.json"
  if [[ -e "${output}" ]]; then
    die 1 "output file already exists: ${output} (move it away or use --in-place)"
  fi
  cat "${tmp}" > "${output}"
  info "wrote merged config: ${output}"
  info "your original file was NOT modified."
  echo "Next: review the file, then copy it to /ventoy/ventoy.json on the USB."
fi
